CREATE TABLE IF NOT EXISTS `PREFIX_achats_clients_sync` (
`id` varchar(128) NOT NULL,
`montant` decimal(17,2) unsigned NOT NULL, 
`date` datetime NOT NULL,
`choixPaiement` set('CB','PA','CH','VI','PR') NOT NULL COMMENT 'credit card, Paypal, Check, Transfer, PR?',
`etat` set('attente','valide','erreur','test') NOT NULL,
`erreurPaybox` varchar(5) DEFAULT NULL,
`erreurPaypal` varchar(5) DEFAULT NULL,
`estAdhesion` set('oui','non') DEFAULT NULL,
`recuFiscal` set('oui','non') DEFAULT NULL,
`commentaire` text,
`URLInterface` varchar(255) NOT NULL, 
`adresseIP` varchar(255) DEFAULT NULL,
`intitule` varchar(255) DEFAULT NULL, 
`panier` text DEFAULT NULL, 
`id_client_boutique` varchar(128) NOT NULL,
`nom` varchar(255) NOT NULL,
`prenom` varchar(255) NOT NULL,
`courriel` varchar(255) NOT NULL,
`telephone` varchar(30) DEFAULT NULL,
`adresse` varchar(255) NOT NULL,
`adresseComplement` varchar(255) DEFAULT NULL,
`codePostal` varchar(16) NOT NULL,
`ville` varchar(255) NOT NULL,
`pays` varchar(255) NOT NULL,
`newsletter` set('oui','non') NOT NULL,
`pasDePapier` set('oui','non') NOT NULL DEFAULT 'non',
`syncDate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
`syncEtat` set('synchronised','tosync','torefresh','error') NOT NULL,
`syncErreur` text NOT NULL,
PRIMARY KEY (`id`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
